force-app/main/default/objects/PH_Assessment__c/PH_Assessment__c.object-meta.xml
<CustomObject>
    <label>PH_Assessment</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>PH_Assesment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PH_Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PH_Assessment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PH_Assessments</relationshipLabel>
    <relationshipName>PH_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PH_Assessment__c/fields/Interview_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Interview_End_Time__c</fullName>
    <label>Interview End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/PH_Assessment__c/fields/Interview_Start__c.field-meta.xml
<CustomField>
    <fullName>Interview_Start__c</fullName>
    <label>Interview Start</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/PH_Assessment__c/fields/OverallPass__c.field-meta.xml
<CustomField>
    <fullName>OverallPass__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OverallPass</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ConductPanelApexControllerTest.cls
// Test for the end assessment button
@isTest
public class ConductPanelApexControllerTest {
    @testSetup
    public static void setup(){
        PanelForceDataCreator.createData(); //does not make assessments
        Id contactId = [SELECT Id FROM Contact LIMIT 1].Id;
        PH_Assessment__c newAssessment = new PH_Assessment__c();
        newAssessment.Contact__c = contactId;
        newAssessment.Interview_Date__c = System.today();
        newAssessment.Interview_Start__c = System.now().time();
        newAssessment.OverallPass__c = true;
        // insert newAssessment
        insert newAssessment;
    }
    @isTest
    public static void setNewStopTimeForAssessmentTest(){
        PH_assessment__c asst = [SELECT Id, Interview_End_Time__c FROM PH_Assessment__c LIMIT 1];
        System.debug('About to call setnewstoptimeforassessment');
        ConductPanelApexController.apexSetNewStopTimeForAssessment(asst.id);
        asst = [SELECT Id, Interview_End_Time__c FROM PH_Assessment__c LIMIT 1]; //get updated asst
        System.assertequals(System.now().time().second(), asst.Interview_End_Time__c.second());
    }
}