force-app/main/default/objects/PH_Assessment__c/PH_Assessment__c.object-meta.xml
<CustomObject>
    <label>PH_Assessment</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>PH_Assesment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PH_Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PH_Assessment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PH_Assessments</relationshipLabel>
    <relationshipName>PH_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PanelCategoriesTests.cls
@isTest
public class PanelCategoriesTests {
    
    @testSetup
    static void setup() {
        // created one test contact 
        Contact newContact = new Contact(FirstName = 'Billy', LastName = 'Bob');
        insert newContact;
        // created one test Assessment
        PH_Assessment__c newAssessment = new PH_Assessment__c( Contact__c = newContact.Id);
        insert newAssessment;
    }
    
    
    @isTest
    static void testgetNumberofTries() {
        Contact c = [SELECT Id FROM Contact];
        PanelCategories.getNumberofTries(c.Id);
    }
}