force-app/main/default/objects/PH_Assessment__c/PH_Assessment__c.object-meta.xml
<CustomObject>
    <label>PH_Assessment</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>PH_Assesment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PH_Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PH_Assessment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PH_Assessments</relationshipLabel>
    <relationshipName>PH_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PH_Assessment__c/fields/Interview_Start__c.field-meta.xml
<CustomField>
    <fullName>Interview_Start__c</fullName>
    <label>Interview Start</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/PH_Assessment__c/fields/OverallPass__c.field-meta.xml
<CustomField>
    <fullName>OverallPass__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OverallPass</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PH_Assessment__c/recordTypes/Panel.recordType-meta.xml
<RecordType>
    <fullName>Panel</fullName>
    <active>true</active>
    <label>Panel</label>
</RecordType>

force-app/main/default/classes/PanelViewTrackMiscController.cls
public with sharing class PanelViewTrackMiscController {

@AuraEnabled
public static List<PH_Assessment__c> fetchAssessments(PH_Assessment__c ass) {

        // Query records from PH_Assessment__c and return query.
        return [SELECT Id, Interview_Date__c, Interview_Start__c, Total_Score__c, OverallPass__c
                FROM PH_Assessment__c
                WHERE Contact__c = :ass.Contact__c];
    }

    public static Id fetchRecordTypeId() {
            return [SELECT Id FROM RecordType WHERE name = 'Panel'][0].Id;
    }
}