force-app/main/default/objects/PH_Assessment__c/PH_Assessment__c.object-meta.xml
<CustomObject>
    <label>PH_Assessment</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>PH_Assesment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PH_Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PH_Assessment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PH_Assessments</relationshipLabel>
    <relationshipName>PH_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PH_Assessment__c/fields/Interview_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Interview_End_Time__c</fullName>
    <label>Interview End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/PH_Assessment__c/fields/Interview_Start__c.field-meta.xml
<CustomField>
    <fullName>Interview_Start__c</fullName>
    <label>Interview Start</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/PH_Assessment__c/fields/InterviewDuration__c.field-meta.xml
<CustomField>
    <fullName>InterviewDuration__c</fullName>
    <defaultValue>60</defaultValue>
    <label>Interview Duration</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PH_Assessment__c/fields/OverallPass__c.field-meta.xml
<CustomField>
    <fullName>OverallPass__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OverallPass</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PH_Assessment__c/fields/Panelist__c.field-meta.xml
<CustomField>
    <fullName>Panelist__c</fullName>
    <defaultValue>&quot;Panelist One&quot;</defaultValue>
    <label>Panelist</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PH_Assessment__c/fields/PanelRound__c.field-meta.xml
<CustomField>
    <fullName>PanelRound__c</fullName>
    <label>Panel Round</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PH_Assessment__c/fields/TrainingTrack__c.field-meta.xml
<CustomField>
    <fullName>TrainingTrack__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training Track</label>
    <referenceTo>PH_TrainingTrack__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PH_Training__c/PH_Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <displayFormat>TRNG-{00000000}</displayFormat>
        <label>PH_ Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PH_Training__c/fields/PH_TrainingTrack__c.field-meta.xml
<CustomField>
    <fullName>PH_TrainingTrack__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PH_TrainingTrack</label>
    <referenceTo>PH_TrainingTrack__c</referenceTo>
    <relationshipLabel>PH_Trainings</relationshipLabel>
    <relationshipName>PH_Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PH_TrainingAssignment__c/PH_TrainingAssignment__c.object-meta.xml
<CustomObject>
    <label>Training Assignment</label>
    <nameField>
        <displayFormat>TA-{00000000}</displayFormat>
        <label>PH_Training  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PH_TrainingAssignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PH_TrainingAssignments</relationshipLabel>
    <relationshipName>PH_TrainingAssignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PH_TrainingAssignment__c/fields/PH_Training__c.field-meta.xml
<CustomField>
    <fullName>PH_Training__c</fullName>
    <label>PH_Training</label>
    <referenceTo>PH_Training__c</referenceTo>
    <relationshipLabel>PH_TrainingAssignments</relationshipLabel>
    <relationshipName>PH_TrainingAssignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PH_TrainingTrack__c/PH_TrainingTrack__c.object-meta.xml
<CustomObject>
    <label>PH_TrainingTrack</label>
    <nameField>
        <label>PH_TrainingTrack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PH_TrainingTracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ConductPanelApexController.cls
public class ConductPanelApexController {
    
    public static Id currentRecordAssessmentId;
    
    @auraEnabled
    public static String apexMakeNewAssessementRecord(Id associateId) {
        // make newAssessment
        PH_Assessment__c newAssessment = new PH_Assessment__c();
        // prepopulate newAssessment fields with known data
        if (associateId != null) {
            newAssessment.Contact__c = associateId;
        }
        newAssessment.Panelist__c = UserInfo.getUserId();
        newAssessment.Interview_Date__c = System.today();
        newAssessment.Interview_Start__c = System.now().time();
        newAssessment.TrainingTrack__c = apexGetTrainingTrack(associateId);
        newAssessment.PanelRound__c = apexGetNumberOfPreviousPanelRounds(associateId) + 1;        
        newAssessment.OverallPass__c = true;
        // insert newAssessment
        insert newAssessment;
        //return Id of newAssessment
        currentRecordAssessmentId = newAssessment.Id;
        return newAssessment.Id;
    }
    
    
    
    @auraEnabled
    public static String apexGetTrainingTrack(Id associateId) {
        // start with id of associate
        // we want to find PH_TrainingTrack__c and return this value
        Id targetTrainingTrack;
        // get (1 record) most recent PH_TrainingAssignment__c for associate
        PH_TrainingAssignment__c mostRecentTrainingAssignmentForAssociate = [SELECT Id, Name, Contact__c, PH_Training__r.PH_TrainingTrack__c  FROM PH_TrainingAssignment__c WHERE Contact__c = :associateId ORDER BY CreatedDate DESC LIMIT 1];
        // get PH_TrainingTrack__c from PH_TrainingAssignment__c for associate
        targetTrainingTrack = mostRecentTrainingAssignmentForAssociate.PH_Training__r.PH_TrainingTrack__c;
        //return targetTrainingTrack
        return targetTrainingTrack;
    }
    
    
    
    @auraEnabled
    public static Integer apexGetNumberOfPreviousPanelRounds(Id associateId) {
        // start with id of associate
        // we want to find count() of previous panels of associateId
        Integer countOfPreviousPanelRounds = [SELECT COUNT() FROM PH_Assessment__c WHERE Contact__c = :associateId];
        // return countOfPreviousPanelRounds
        return countOfPreviousPanelRounds;
    }
    
    
    
    @auraEnabled
    public static Time apexSetNewStartTime(Id assessmentId) {
        // query for record
        PH_Assessment__c workingAssessment = [SELECT Id, Interview_Start__c FROM PH_Assessment__c WHERE Id = :assessmentId];
        // update time
        Time currentTime = System.now().time();
        workingAssessment.Interview_Start__c = currentTime;
        update workingAssessment;
        // return currentTime
        return currentTime;
    }
    
    @auraEnabled
    public static Time setNewStopTimeForAssessment(Id assessmentId) {
        PH_Assessment__c finishedAssessment = [SELECT Id, Interview_End_Time__c, Interview_Start__c, InterviewDuration__c FROM PH_Assessment__c WHERE Id =: assessmentId];
        Time endTime = System.now().time();
        finishedAssessment.Interview_End_Time__c = endTime;
        double minuteDuration = finishedAssessment.interview_end_time__c.minute() - finishedAssessment.interview_start__c.minute();
        
        finishedAssessment.InterviewDuration__c = minuteDuration;
        update finishedAssessment;
        return endTime;
        
    }
    
   
        
    
    
}