force-app/main/default/objects/PH_Assessment__c/PH_Assessment__c.object-meta.xml
<CustomObject>
    <label>PH_Assessment</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>PH_Assesment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PH_Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PH_Assessment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PH_Assessments</relationshipLabel>
    <relationshipName>PH_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PH_Assessment__c/recordTypes/Panel.recordType-meta.xml
<RecordType>
    <fullName>Panel</fullName>
    <active>true</active>
    <label>Panel</label>
</RecordType>

force-app/main/default/objects/PH_Training__c/PH_Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <displayFormat>TRNG-{00000000}</displayFormat>
        <label>PH_ Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PH_TrainingAssignment__c/PH_TrainingAssignment__c.object-meta.xml
<CustomObject>
    <label>Training Assignment</label>
    <nameField>
        <displayFormat>TA-{00000000}</displayFormat>
        <label>PH_Training  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PH_TrainingAssignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PH_TrainingAssignments</relationshipLabel>
    <relationshipName>PH_TrainingAssignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PH_TrainingAssignment__c/fields/PH_Training__c.field-meta.xml
<CustomField>
    <fullName>PH_Training__c</fullName>
    <label>PH_Training</label>
    <referenceTo>PH_Training__c</referenceTo>
    <relationshipLabel>PH_TrainingAssignments</relationshipLabel>
    <relationshipName>PH_TrainingAssignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/EmailTrainerHelper.cls
public with sharing class EmailTrainerHelper {
    public static void ETrainer(List<PH_Assessment__c> phAList) {
        List<ID> cIDList = new List<ID>();
        ID rID = [SELECT id FROM recordtype WHERE name = 'Panel'][0].id;
        for (PH_Assessment__c phA : phAList) {
            if (phA.recordtypeID == rID) cIDList.add(phA.Contact__c);
        }
        List<Contact> cList = new List<Contact>();
        for (Contact c : [SELECT Name FROM Contact where ID IN :cIDList]) {
            cList.add(c);
        }
        List<ph_trainingassignment__c> phTList = new List<ph_trainingassignment__c>();
        for (ph_trainingassignment__c phT : [SELECT contact__c, PH_Training__r.ownerID
                                                FROM ph_trainingassignment__c
                                                WHERE Contact__c IN :cIDList]) {
            phTList.add(phT);
        }
        List<ID> phTIDList = new List<ID>();
        for (Ph_TrainingAssignment__c phT : phTList) {
            phTIDList.add(phT.PH_Training__r.ownerID);
        }
        List<User> uList = new List<User>();
        for (User u : [SELECT id, email FROM user WHERE id in :phTIDList]) {
            uList.add(u);
        }
    

        for (Contact c : cList) {
            string [] toaddress;
            for (ph_trainingassignment__c phT : phTList) {
                if (phT.contact__c == c.id) {
                    for (User u : uList) {
                        if (u.id == phT.PH_Training__r.ownerID) toaddress= new String[]{u.email}; 
                    }
                }
            }
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            email.setSubject('Candidate has taken their panel.');

            String sCandidate = 'Candidate has taken their panel.\n' + c.Name;
   
            email.setPlainTextBody(sCandidate);
            email.setToAddresses(toaddress);
            // Messaging.sendEmail(New Messaging.SingleEmailMessage[]{email});
        }
    }
}