force-app/main/default/objects/PH_Assessment__c/PH_Assessment__c.object-meta.xml
<CustomObject>
    <label>PH_Assessment</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>PH_Assesment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PH_Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Stamp__c/Time_Stamp__c.object-meta.xml
<CustomObject>
    <label>Time Stamp</label>
    <nameField>
        <label>Time_Stamp Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Stamps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Stamp__c/fields/PH_Assessment__c.field-meta.xml
<CustomField>
    <fullName>PH_Assessment__c</fullName>
    <label>PH_Assessment</label>
    <referenceTo>PH_Assessment__c</referenceTo>
    <relationshipLabel>Time Stamps</relationshipLabel>
    <relationshipName>Time_Stamps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/timeStampClass.cls
public with sharing class timeStampClass {
  @AuraEnabled
  public static void insertTimeStamp(List<Integer> sTimeStamp, PH_Assessment__c phAss){
      List<Time_Stamp__c> tsList = new List<Time_Stamp__c>();     
      system.debug('Inside Function');
      for(Integer stm : sTimeStamp){
        Time_Stamp__c ts = new Time_Stamp__c();
         ts.Date_Time__c = DateTime.valueOf(stm);
         ts.PH_Assessment__c = phAss.Id;
         System.debug('Inside for loop');
         tsList.add(ts);
      }

insert tsList;
  }
}