force-app/main/default/objects/PanelCategory__c/PanelCategory__c.object-meta.xml
<CustomObject>
    <label>Panel Category</label>
    <nameField>
        <label>Panel Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Panel Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PanelCategory__c/fields/PH_TrainingTrack__c.field-meta.xml
<CustomField>
    <fullName>PH_TrainingTrack__c</fullName>
    <label>PH_TrainingTrack</label>
    <referenceTo>PH_TrainingTrack__c</referenceTo>
    <relationshipLabel>Panel Categories</relationshipLabel>
    <relationshipName>Panel_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PH_Assessment__c/PH_Assessment__c.object-meta.xml
<CustomObject>
    <label>PH_Assessment</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>PH_Assesment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PH_Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PH_Assessment__c/fields/Panelist__c.field-meta.xml
<CustomField>
    <fullName>Panelist__c</fullName>
    <defaultValue>&quot;Panelist One&quot;</defaultValue>
    <label>Panelist</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PH_Assessment__c/recordTypes/Panel.recordType-meta.xml
<RecordType>
    <fullName>Panel</fullName>
    <active>true</active>
    <label>Panel</label>
</RecordType>

force-app/main/default/objects/PH_TrainingTrack__c/PH_TrainingTrack__c.object-meta.xml
<CustomObject>
    <label>PH_TrainingTrack</label>
    <nameField>
        <label>PH_TrainingTrack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PH_TrainingTracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Stamp__c/Time_Stamp__c.object-meta.xml
<CustomObject>
    <label>Time Stamp</label>
    <nameField>
        <label>Time_Stamp Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Stamps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Stamp__c/fields/PanelCategory__c.field-meta.xml
<CustomField>
    <fullName>PanelCategory__c</fullName>
    <label>PanelCategory</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Time_Stamp__c/fields/PH_Assessment__c.field-meta.xml
<CustomField>
    <fullName>PH_Assessment__c</fullName>
    <label>PH_Assessment</label>
    <referenceTo>PH_Assessment__c</referenceTo>
    <relationshipLabel>Time Stamps</relationshipLabel>
    <relationshipName>Time_Stamps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/createTimestampControllerTest.cls
@isTest
public class createTimestampControllerTest {
	@TestSetup
    public static void setup(){
        Contact contact = new Contact(LastName='contact1');
        PH_Assessment__c assessment = new PH_Assessment__c(Panelist__c=contact.id);
        PH_TrainingTrack__c trainingTrack = new PH_TrainingTrack__c(Name='Training Track 1'); // must create trainingTrack as it is the parent of panelCategory
        insert trainingTrack;
        
        PanelCategory__c panelCategory = new PanelCategory__c(Name='Panel Category 1', PH_TrainingTrack__c=trainingTrack.Id );
        insert contact;
        insert assessment;
       // insert trainingTrack;
        insert panelCategory;
    }
    
    @isTest
    public static void saveTimestampTest(){
        Integer initialNumTimestamps = [SELECT Count() FROM Time_Stamp__c]; //inital number of saved timestamps
        PH_Assessment__c assessment = [SELECT Id FROM PH_Assessment__c LIMIT 1];
        PanelCategory__c panelCategory = [SELECT Id FROM PanelCategory__c LIMIT 1]; 
        createTimestampController.saveTimestamp(assessment.Id, panelCategory.Id); //create and save timestamp
        Integer finalNumTimestamps = [SELECT Count() FROM Time_Stamp__c]; //final number of saved timestamps
        System.assertEquals(initialNumTimestamps+1, finalNumTimestamps);
        
    }
}