force-app/main/default/objects/PanelCategory__c/PanelCategory__c.object-meta.xml
<CustomObject>
    <label>Panel Category</label>
    <nameField>
        <label>Panel Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Panel Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PanelCategory__c/fields/maxScore__c.field-meta.xml
<CustomField>
    <fullName>maxScore__c</fullName>
    <label>Max Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PanelCategory__c/fields/PH_TrainingTrack__c.field-meta.xml
<CustomField>
    <fullName>PH_TrainingTrack__c</fullName>
    <label>PH_TrainingTrack</label>
    <referenceTo>PH_TrainingTrack__c</referenceTo>
    <relationshipLabel>Panel Categories</relationshipLabel>
    <relationshipName>Panel_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PH_TrainingTrack__c/PH_TrainingTrack__c.object-meta.xml
<CustomObject>
    <label>PH_TrainingTrack</label>
    <nameField>
        <label>PH_TrainingTrack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PH_TrainingTracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CreateCategoriesController.cls
public class CreateCategoriesController {
 
    @AuraEnabled
    public static List<PanelCategory__c> getCategories(){
        return [SELECT Id, Name, maxScore__c, PH_TrainingTrack__c
                FROM PanelCategory__c];
    }
    
    @AuraEnabled
    public static PanelCategory__c saveCategories(PanelCategory__c panel) {
        // Need to ask if this is correct way of doing this. This will save all new panels to database and we
        // want to create new categories for tracks without seeing exisiting categories.
        // Fix so user has ability to save a category to the proper track.
        if (panel.PH_TrainingTrack__c == null) {
            panel.PH_TrainingTrack__c = [SELECT Id FROM PH_TrainingTrack__c LIMIT 1].Id;
        }
        PanelCategory__c result;
        if (panel.Id == null) {
            result = panel;
        } else {
            result = null;
        }

        upsert panel;
        return result;
    }

    @AuraEnabled
    public static PanelCategory__c removeCategory(PanelCategory__c panel) {
        delete panel;
        return panel;
    }
    
}