force-app/main/default/objects/PanelCategory__c/PanelCategory__c.object-meta.xml
<CustomObject>
    <label>Panel Category</label>
    <nameField>
        <label>Panel Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Panel Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PanelCategory__c/fields/maxScore__c.field-meta.xml
<CustomField>
    <fullName>maxScore__c</fullName>
    <label>Max Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PanelCategory__c/fields/PH_TrainingTrack__c.field-meta.xml
<CustomField>
    <fullName>PH_TrainingTrack__c</fullName>
    <label>PH_TrainingTrack</label>
    <referenceTo>PH_TrainingTrack__c</referenceTo>
    <relationshipLabel>Panel Categories</relationshipLabel>
    <relationshipName>Panel_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PH_TrainingTrack__c/PH_TrainingTrack__c.object-meta.xml
<CustomObject>
    <label>PH_TrainingTrack</label>
    <nameField>
        <label>PH_TrainingTrack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PH_TrainingTracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/testCreateCategoriesController.cls
@isTest(seeAllData=true)
public with sharing class testCreateCategoriesController {
    
    @isTest static void testCategories() {
        System.assertEquals([SELECT Id, Name, maxScore__c, PH_TrainingTrack__c
                            FROM PanelCategory__c].size(), CreateCategoriesController.getCategories().size());

        PanelCategory__c pc = new PanelCategory__c();
        pc.Name = 'Test pc';
        pc.maxScore__c = 30;
        pc.Status__c = false;
        // pc.PH_TrainingTrack__c = [SELECT Id FROM PH_TrainingTrack LIMIT 1];

        PanelCategory__c res1 = CreateCategoriesController.saveCategories(pc);
        System.assertNotEquals(null, res1);
        System.assertNotEquals(null, res1.Id);

        PanelCategory__c res2 = CreateCategoriesController.saveCategories(res1);
        System.assertEquals(null, res2);

        PanelCategory__c delres = CreateCategoriesController.removeCategory(res1);
        System.assertNotEquals(null, delres);
    }
}