force-app/main/default/objects/PanelCategory__c/PanelCategory__c.object-meta.xml
<CustomObject>
    <label>Panel Category</label>
    <nameField>
        <label>Panel Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Panel Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PanelCategory__c/fields/maxScore__c.field-meta.xml
<CustomField>
    <fullName>maxScore__c</fullName>
    <label>Max Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PanelCategory__c/fields/PH_TrainingTrack__c.field-meta.xml
<CustomField>
    <fullName>PH_TrainingTrack__c</fullName>
    <label>PH_TrainingTrack</label>
    <referenceTo>PH_TrainingTrack__c</referenceTo>
    <relationshipLabel>Panel Categories</relationshipLabel>
    <relationshipName>Panel_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PH_TrainingTrack__c/PH_TrainingTrack__c.object-meta.xml
<CustomObject>
    <label>PH_TrainingTrack</label>
    <nameField>
        <label>PH_TrainingTrack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PH_TrainingTracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestCreateCategoriesController.cls
@isTest
public class TestCreateCategoriesController 

{
    @testSetup
	public static void setup()
    {
        List<PH_TrainingTrack__c> tracksToInsert = new List<PH_TrainingTrack__c>();
        PH_TrainingTrack__c typeOfTrack = new PH_TrainingTrack__c(Name='Track1');
        tracksToInsert.add(typeOfTrack);
        insert typeOfTrack;

        PanelCategory__c panelId;
        
		PanelCategory__c panelCategories = new PanelCategory__c(Name = 'Panel1',maxScore__c = 80,PH_TrainingTrack__c=typeOfTrack.Id);
        insert panelCategories;
    }
    @isTest
    public static void saveCategoriesTest()
    {
       /*
        List<PH_TrainingTrack__c> track = [SELECT Id FROM PH_TrainingTrack__c];
        List <PanelCategory__c> panels = [SELECT PH_TrainingTrack__c FROM PanelCategory__c];
        
  		for(PH_TrainingTrack__c tt : track)
        {
            for(PanelCategory__c pc : panels)
            {   
            
        		System.assertEquals(pc.PH_TrainingTrack__c, tt.Id);
            }
        }
        */
        List<PH_TrainingTrack__c> tracksToInsert = [SELECT Id FROM PH_TrainingTrack__c];
        PanelCategory__c panelCategories = new PanelCategory__c();
		for(PH_TrainingTrack__c newTrainingTrack : tracksToInsert)
        {
        	 panelCategories = new PanelCategory__c(Name = 'Panel2',maxScore__c = 85,PH_TrainingTrack__c = newTrainingTrack.Id);
        }
        insert panelCategories;
                List <PanelCategory__c> panels = [SELECT Name FROM PanelCategory__c WHERE Name ='Panel2'];
        	for(PanelCategory__c category : panels)
            { 
				System.assertEquals('Panel2', category.Name);
                
            }
    }
    @isTest
    public static void removeCategoryTest()
    {
        List <PanelCategory__c> panels = [SELECT Name FROM PanelCategory__c];
		delete panels;
            panels = [SELECT Name FROM PanelCategory__c];

        System.assertEquals(0, panels.size());
    }
}