force-app/main/default/objects/AssessmentLineItem__c/AssessmentLineItem__c.object-meta.xml
<CustomObject>
    <label>Assessment Line Item</label>
    <nameField>
        <displayFormat>ALI-{0000000}</displayFormat>
        <label>Assessment Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AssessmentLineItem__c/fields/PanelCategory__c.field-meta.xml
<CustomField>
    <fullName>PanelCategory__c</fullName>
    <label>Panel Category</label>
    <referenceTo>PanelCategory__c</referenceTo>
    <relationshipName>Assessment_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PanelCategory__c/PanelCategory__c.object-meta.xml
<CustomObject>
    <label>Panel Category</label>
    <nameField>
        <label>Panel Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Panel Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PanelCategory__c/fields/PH_TrainingTrack__c.field-meta.xml
<CustomField>
    <fullName>PH_TrainingTrack__c</fullName>
    <label>PH_TrainingTrack</label>
    <referenceTo>PH_TrainingTrack__c</referenceTo>
    <relationshipLabel>Panel Categories</relationshipLabel>
    <relationshipName>Panel_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PH_TrainingTrack__c/PH_TrainingTrack__c.object-meta.xml
<CustomObject>
    <label>PH_TrainingTrack</label>
    <nameField>
        <label>PH_TrainingTrack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PH_TrainingTracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/testTrackController.cls
@isTest
public class testTrackController {
    @isTest
    public Static void testTrackController() {
        // test methods getTrack, getContact
        Contact c = new Contact();
        TrackController tc = new TrackController();
        String s;
        PH_TrainingTrack__c tt = new PH_TrainingTrack__c();

        c.Lastname = 'test 1';
        tt.Name = 'test 2';
        insert tt;
        insert c;
        // test 2 methods.
        try {
            tt = TrackController.getTrack(c.Id);
        } catch (ListException e) {
            System.debug('List index out of bounds probably: '  + ' ' + e);
        }

        try {
            s = TrackController.getContact(c.Id);
        } catch (StringException e) {
            System.debug('getContact not returning string: ' + s);
        }

        try {
            System.assert(c.Id != null);
            System.assert(tt.Name != null);
            System.assert(s != null);
        } catch (AssertException e) {
            System.debug('Chech assertion: ' + ' ' + e);
            System.debug('s: ' + s + ' ' + 'c.Id: ' + ' ' + c.Id + ' ' + 'tt.Name' + ' ' + tt.Name);
        }
        
        // test cleanup
        Database.delete(c);
        Database.delete(tt);
    }

    @isTest
    Public Static Void testCreateData() {
        Contact c = new Contact();
        List<AssessmentLineItem__c> loali = new List<AssessmentLineItem__c>();
        PH_TrainingTrack__c tt = new PH_TrainingTrack__c();
        //TrackController tc = new TrackController();

        c.Lastname = 'test';
        tt.Name = 'test';

        // needs DML insert in order to use c.Id to check createData()
        insert c;
        insert tt;

        // test a.Id and that Id is not null.
        loali = TrackController.createData(c.Id, tt.Id);
        System.assert(c.Id != null);
        System.assert(tt.Id != null);
        System.assert(loali != null);

        try {
            for (AssessmentLineItem__c ali : loali) {
                System.assert(ali.Name != null);
                System.assert(ali.PanelCategory__c != null);
            }
        } catch (ListException e) {
            System.debug('ListException: ' + e);
        } catch (Exception e) {
            System.debug('General Exception: ' + e);
        }

        Database.delete(c);
        Database.delete(tt);
    }
}