force-app/main/default/objects/AssessmentLineItem__c/AssessmentLineItem__c.object-meta.xml
<CustomObject>
    <label>Assessment Line Item</label>
    <nameField>
        <displayFormat>ALI-{0000000}</displayFormat>
        <label>Assessment Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AssessmentLineItem__c/fields/PH_Assessment__c.field-meta.xml
<CustomField>
    <fullName>PH_Assessment__c</fullName>
    <label>PH_Assessment</label>
    <referenceTo>PH_Assessment__c</referenceTo>
    <relationshipLabel>Panel Categories</relationshipLabel>
    <relationshipName>Assessment_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PH_Assessment__c/PH_Assessment__c.object-meta.xml
<CustomObject>
    <label>PH_Assessment</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>PH_Assesment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PH_Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PH_Assessment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PH_Assessments</relationshipLabel>
    <relationshipName>PH_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PH_Training__c/PH_Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <displayFormat>TRNG-{00000000}</displayFormat>
        <label>PH_ Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PH_Training__c/fields/PH_TrainingTrack__c.field-meta.xml
<CustomField>
    <fullName>PH_TrainingTrack__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PH_TrainingTrack</label>
    <referenceTo>PH_TrainingTrack__c</referenceTo>
    <relationshipLabel>PH_Trainings</relationshipLabel>
    <relationshipName>PH_Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PH_TrainingAssignment__c/PH_TrainingAssignment__c.object-meta.xml
<CustomObject>
    <label>Training Assignment</label>
    <nameField>
        <displayFormat>TA-{00000000}</displayFormat>
        <label>PH_Training  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PH_TrainingAssignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PH_TrainingAssignments</relationshipLabel>
    <relationshipName>PH_TrainingAssignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PH_TrainingAssignment__c/fields/PH_Training__c.field-meta.xml
<CustomField>
    <fullName>PH_Training__c</fullName>
    <label>PH_Training</label>
    <referenceTo>PH_Training__c</referenceTo>
    <relationshipLabel>PH_TrainingAssignments</relationshipLabel>
    <relationshipName>PH_TrainingAssignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PH_TrainingTrack__c/PH_TrainingTrack__c.object-meta.xml
<CustomObject>
    <label>PH_TrainingTrack</label>
    <nameField>
        <label>PH_TrainingTrack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PH_TrainingTracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PanelCategories.cls
public without sharing class PanelCategories {
    // Saving the assessment
    @AuraEnabled
    public static void saveAssessment(List<AssessmentLineItem__c> aLIList, PH_Assessment__c assessment){
        System.debug('aLIList: ' + aLIList);
        System.debug('assessment: ' + assessment);
        insert aLIList;
        insert assessment;
    }

    // Retrieve the track that a candidate is on
    // Question: there are multiple tracks per candidate why do we only select the first one
    @AuraEnabled
    public static String getTrack(ID contactID){
        return [SELECT PH_TrainingTrack__r.Name
        FROM PH_Training__c
        WHERE ID IN (SELECT PH_Training__c FROM PH_TrainingAssignment__c WHERE Contact__c = :contactID)][0].PH_TrainingTrack__r.Name;
    }

    // Retrieving the number of panels that was taken by the candidate
    @AuraEnabled
    public static Integer getNumberofTries(ID contactID){
        return (Integer)[SELECT Contact__c, COUNT(ID) c 
        FROM PH_Assessment__c
        WHERE Contact__c = :contactID
        GROUP BY Contact__c][0].get('c');
    }
}