force-app/main/default/objects/AssessmentLineItem__c/AssessmentLineItem__c.object-meta.xml
<CustomObject>
    <label>Assessment Line Item</label>
    <nameField>
        <displayFormat>ALI-{0000000}</displayFormat>
        <label>Assessment Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AssessmentLineItem__c/fields/Interviewed__c.field-meta.xml
<CustomField>
    <fullName>Interviewed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Passed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AssessmentLineItem__c/fields/maxScore__c.field-meta.xml
<CustomField>
    <fullName>maxScore__c</fullName>
    <label>maxScore</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AssessmentLineItem__c/fields/PanelCategory__c.field-meta.xml
<CustomField>
    <fullName>PanelCategory__c</fullName>
    <label>Panel Category</label>
    <referenceTo>PanelCategory__c</referenceTo>
    <relationshipName>Assessment_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AssessmentLineItem__c/fields/PH_Assessment__c.field-meta.xml
<CustomField>
    <fullName>PH_Assessment__c</fullName>
    <label>PH_Assessment</label>
    <referenceTo>PH_Assessment__c</referenceTo>
    <relationshipLabel>Panel Categories</relationshipLabel>
    <relationshipName>Assessment_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PanelCategory__c/PanelCategory__c.object-meta.xml
<CustomObject>
    <label>Panel Category</label>
    <nameField>
        <label>Panel Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Panel Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PanelCategory__c/fields/maxScore__c.field-meta.xml
<CustomField>
    <fullName>maxScore__c</fullName>
    <label>Max Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PanelCategory__c/fields/PH_TrainingTrack__c.field-meta.xml
<CustomField>
    <fullName>PH_TrainingTrack__c</fullName>
    <label>PH_TrainingTrack</label>
    <referenceTo>PH_TrainingTrack__c</referenceTo>
    <relationshipLabel>Panel Categories</relationshipLabel>
    <relationshipName>Panel_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PH_Assessment__c/PH_Assessment__c.object-meta.xml
<CustomObject>
    <label>PH_Assessment</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>PH_Assesment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PH_Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PH_TrainingTrack__c/PH_TrainingTrack__c.object-meta.xml
<CustomObject>
    <label>PH_TrainingTrack</label>
    <nameField>
        <label>PH_TrainingTrack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PH_TrainingTracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/InterviewMainScoreApexControllerTests.cls
@isTest
public class InterviewMainScoreApexControllerTests {

    @testSetup static void setup(){
        
        //List<PH_TrainingTrack__c> Tracks = new List<PH_TrainingTrack__c>();
        PH_TrainingTrack__c Track = [SELECT Id FROM PH_TrainingTrack__c];
        //Tracks.add(new PH_TrainingTrack__c(Name='SF'));
        
        
        insert Track;
        
        List<PanelCategory__c> pcs = new List<PanelCategory__c>();
        
        pcs.add(new PanelCategory__c(Name='Testing', PH_TrainingTrack__c= Track.Id, maxScore__c=10, Status__c=True));
        pcs.add(new PanelCategory__c(Name='Testing2', PH_TrainingTrack__c=Track.Id, maxScore__c=10, Status__c=True));
        pcs.add(new PanelCategory__c(Name='Testing3', PH_TrainingTrack__c=Track.Id, maxScore__c=10, Status__c=True));
        
        insert pcs;

        PH_Assessment__c asm = [SELECT Id FROM PH_Assessment__c];
        //List<PH_Assessment__c> asms = new List<PH_Assessment__c>();

        //asms.add(new PH_Assessment__c())
        insert asm;
        
        List<AssessmentLineItem__c> alis = new List<AssessmentLineItem__c>();
        
        alis.add(new AssessmentLineItem__c(Name='Test1', Comment__c='Test1', maxScore__c=10, PanelCategory__c=pcs[0].id, Interviewed__c=True, PH_Assessment__c=asm.Id, Score__c=9, Status__c=True));
        alis.add(new AssessmentLineItem__c(Name='Test2', Comment__c='Test2', maxScore__c=10, PanelCategory__c=pcs[1].id, Interviewed__c=True, PH_Assessment__c=asm.Id, Score__c=6, Status__c=True));
        alis.add(new AssessmentLineItem__c(Name='Test3', Comment__c='Test3', maxScore__c=10, PanelCategory__c=pcs[2].id, Interviewed__c=True, PH_Assessment__c=asm.Id, Score__c=8, Status__c=True));
        
        insert alis;
    }

	@isTest
    static void testAll() {
        InterviewMainScoreApexController.updateCategories([SELECT Id, Name FROM AssessmentLineItem__c LIMIT 1]);
    }
}