force-app/main/default/objects/AssessmentLineItem__c/AssessmentLineItem__c.object-meta.xml
<CustomObject>
    <label>Assessment Line Item</label>
    <nameField>
        <displayFormat>ALI-{0000000}</displayFormat>
        <label>Assessment Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AssessmentLineItem__c/fields/Interviewed__c.field-meta.xml
<CustomField>
    <fullName>Interviewed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Passed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AssessmentLineItem__c/fields/maxScore__c.field-meta.xml
<CustomField>
    <fullName>maxScore__c</fullName>
    <label>maxScore</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AssessmentLineItem__c/fields/PanelCategory__c.field-meta.xml
<CustomField>
    <fullName>PanelCategory__c</fullName>
    <label>Panel Category</label>
    <referenceTo>PanelCategory__c</referenceTo>
    <relationshipName>Assessment_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AssessmentLineItem__c/fields/PH_Assessment__c.field-meta.xml
<CustomField>
    <fullName>PH_Assessment__c</fullName>
    <label>PH_Assessment</label>
    <referenceTo>PH_Assessment__c</referenceTo>
    <relationshipLabel>Panel Categories</relationshipLabel>
    <relationshipName>Assessment_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PanelCategory__c/PanelCategory__c.object-meta.xml
<CustomObject>
    <label>Panel Category</label>
    <nameField>
        <label>Panel Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Panel Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PanelCategory__c/fields/maxScore__c.field-meta.xml
<CustomField>
    <fullName>maxScore__c</fullName>
    <label>Max Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PanelCategory__c/fields/PH_TrainingTrack__c.field-meta.xml
<CustomField>
    <fullName>PH_TrainingTrack__c</fullName>
    <label>PH_TrainingTrack</label>
    <referenceTo>PH_TrainingTrack__c</referenceTo>
    <relationshipLabel>Panel Categories</relationshipLabel>
    <relationshipName>Panel_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PH_Assessment__c/PH_Assessment__c.object-meta.xml
<CustomObject>
    <label>PH_Assessment</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>PH_Assesment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PH_Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PH_Assessment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PH_Assessments</relationshipLabel>
    <relationshipName>PH_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PH_Training__c/PH_Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <displayFormat>TRNG-{00000000}</displayFormat>
        <label>PH_ Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PH_Training__c/fields/PH_TrainingTrack__c.field-meta.xml
<CustomField>
    <fullName>PH_TrainingTrack__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PH_TrainingTrack</label>
    <referenceTo>PH_TrainingTrack__c</referenceTo>
    <relationshipLabel>PH_Trainings</relationshipLabel>
    <relationshipName>PH_Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PH_TrainingAssignment__c/PH_TrainingAssignment__c.object-meta.xml
<CustomObject>
    <label>Training Assignment</label>
    <nameField>
        <displayFormat>TA-{00000000}</displayFormat>
        <label>PH_Training  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PH_TrainingAssignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PH_TrainingAssignments</relationshipLabel>
    <relationshipName>PH_TrainingAssignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PH_TrainingAssignment__c/fields/PH_Training__c.field-meta.xml
<CustomField>
    <fullName>PH_Training__c</fullName>
    <label>PH_Training</label>
    <referenceTo>PH_Training__c</referenceTo>
    <relationshipLabel>PH_TrainingAssignments</relationshipLabel>
    <relationshipName>PH_TrainingAssignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PH_TrainingTrack__c/PH_TrainingTrack__c.object-meta.xml
<CustomObject>
    <label>PH_TrainingTrack</label>
    <nameField>
        <label>PH_TrainingTrack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PH_TrainingTracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Stamp__c/Time_Stamp__c.object-meta.xml
<CustomObject>
    <label>Time Stamp</label>
    <nameField>
        <label>Time_Stamp Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Stamps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Stamp__c/fields/PanelCategory__c.field-meta.xml
<CustomField>
    <fullName>PanelCategory__c</fullName>
    <label>PanelCategory</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Time_Stamp__c/fields/PH_Assessment__c.field-meta.xml
<CustomField>
    <fullName>PH_Assessment__c</fullName>
    <label>PH_Assessment</label>
    <referenceTo>PH_Assessment__c</referenceTo>
    <relationshipLabel>Time Stamps</relationshipLabel>
    <relationshipName>Time_Stamps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/testData.cls
@isTest(SeeAllData=True)
public with sharing class testData {
   /* @isTest(SeeAllData=True)
    public Static Void testData() {
        PH_TrainingTrack__c tt = new PH_TrainingTrack__c();
        tt.Name = 'test';
        insert tt;

        Contact associate1 = new Contact();
        associate1.Lastname = 'Smith';
        //associate1.Lastname = 'McTechnical';
        insert associate1;

        PH_Training__c t = new PH_Training__c();
        t.Name = 'test';
        t.PH_TrainingTrack__c = 'test';
        insert t;

        PH_TrainingAssignment__c ta = new PH_TrainingAssignment__c();
        ta.Contact__c = '';
        ta.PH_Training__c = 'test';
        ta.Name = 'test';
        insert ta;

        PH_Assessment__c a = new PH_Assessment__c();
        a.Contact__c = 'Techy McTechnical';
        a.OwnerId = 'test';
        a.Name = 'test';
        //a.RecordTypeId = 'test';
        insert a;

        AssessmentLineItem__c ali = new AssessmentLineItem__c();
        ali.Name = 'test';
        ali.Interviewed__c = True;
        ali.maxScore__c = 9;
        ali.PanelCategory__c = 'test';
        ali.PH_Assessment__c = 'test';
        ali.Score__c = 9;
        ali.Status__c = True;
        insert ali;

        PanelCategory__c pc = new PanelCategory__c();
        pc.Status__c = True;
        pc.Name = 'test';
        pc.PH_TrainingTrack__c = 'test';
        pc.Status__c = True;
        insert pc;

//        Scorecard sc = new Scorecard();
//        sc.Description = 'test';
//        sc.Name =' test ';
//        //sc.ScorecardId = 'test'; // master detail
//        //sc.TargetEntityId = 'test'; // lookup account
//        insert sc;

//        ScorecardAssociation sa = new ScorecardAssociation();
//        //sm.ScorecardId = 'test'; // master detail scorecard
//        //sc.TargetEntityId = 'test'; // lookup account
//        insert sa;

//        ScorecardMetric sm = new ScorecardMetric();
//        sm.Category = 'test';
//        sm.Description = 'test';
//        sm.Name = 'test';
//        //sm.ReportId = 'test'; // lookup report
//        //sm.ScorecardId = 'test'; // master detail scorecard
//        insert sm;

        Time_Stamp__c ts = new Time_Stamp__c();
        Datetime m = Datetime.newInstance(2019, 4, 1);
        ts.Date_Time__c = m;
        //ts.PH_Assessment__c = 'test'; // master detail PH_Assessment
        ts.Name = 'test';
        insert ts;

        // or for each object insert 'test';
    }*/
}