force-app/main/default/objects/AssessmentLineItem__c/AssessmentLineItem__c.object-meta.xml
<CustomObject>
    <label>Assessment Line Item</label>
    <nameField>
        <displayFormat>ALI-{0000000}</displayFormat>
        <label>Assessment Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AssessmentLineItem__c/fields/Interviewed__c.field-meta.xml
<CustomField>
    <fullName>Interviewed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Passed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AssessmentLineItem__c/fields/maxScore__c.field-meta.xml
<CustomField>
    <fullName>maxScore__c</fullName>
    <label>maxScore</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AssessmentLineItem__c/fields/PanelCategory__c.field-meta.xml
<CustomField>
    <fullName>PanelCategory__c</fullName>
    <label>Panel Category</label>
    <referenceTo>PanelCategory__c</referenceTo>
    <relationshipName>Assessment_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AssessmentLineItem__c/fields/PanelCategoryName__c.field-meta.xml
<CustomField>
    <fullName>PanelCategoryName__c</fullName>
    <label>PanelCategoryName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AssessmentLineItem__c/fields/PH_Assessment__c.field-meta.xml
<CustomField>
    <fullName>PH_Assessment__c</fullName>
    <label>PH_Assessment</label>
    <referenceTo>PH_Assessment__c</referenceTo>
    <relationshipLabel>Panel Categories</relationshipLabel>
    <relationshipName>Assessment_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PanelCategory__c/PanelCategory__c.object-meta.xml
<CustomObject>
    <label>Panel Category</label>
    <nameField>
        <label>Panel Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Panel Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PanelCategory__c/fields/maxScore__c.field-meta.xml
<CustomField>
    <fullName>maxScore__c</fullName>
    <label>Max Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PanelCategory__c/fields/PH_TrainingTrack__c.field-meta.xml
<CustomField>
    <fullName>PH_TrainingTrack__c</fullName>
    <label>PH_TrainingTrack</label>
    <referenceTo>PH_TrainingTrack__c</referenceTo>
    <relationshipLabel>Panel Categories</relationshipLabel>
    <relationshipName>Panel_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PH_Assessment__c/PH_Assessment__c.object-meta.xml
<CustomObject>
    <label>PH_Assessment</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>PH_Assesment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PH_Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PH_Assessment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PH_Assessments</relationshipLabel>
    <relationshipName>PH_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PH_Assessment__c/recordTypes/Panel.recordType-meta.xml
<RecordType>
    <fullName>Panel</fullName>
    <active>true</active>
    <label>Panel</label>
</RecordType>

force-app/main/default/objects/PH_Training__c/PH_Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <displayFormat>TRNG-{00000000}</displayFormat>
        <label>PH_ Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PH_Training__c/fields/PH_TrainingTrack__c.field-meta.xml
<CustomField>
    <fullName>PH_TrainingTrack__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PH_TrainingTrack</label>
    <referenceTo>PH_TrainingTrack__c</referenceTo>
    <relationshipLabel>PH_Trainings</relationshipLabel>
    <relationshipName>PH_Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PH_TrainingAssignment__c/PH_TrainingAssignment__c.object-meta.xml
<CustomObject>
    <label>Training Assignment</label>
    <nameField>
        <displayFormat>TA-{00000000}</displayFormat>
        <label>PH_Training  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PH_TrainingAssignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PH_TrainingAssignments</relationshipLabel>
    <relationshipName>PH_TrainingAssignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PH_TrainingAssignment__c/fields/PH_Training__c.field-meta.xml
<CustomField>
    <fullName>PH_Training__c</fullName>
    <label>PH_Training</label>
    <referenceTo>PH_Training__c</referenceTo>
    <relationshipLabel>PH_TrainingAssignments</relationshipLabel>
    <relationshipName>PH_TrainingAssignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PH_TrainingTrack__c/PH_TrainingTrack__c.object-meta.xml
<CustomObject>
    <label>PH_TrainingTrack</label>
    <nameField>
        <label>PH_TrainingTrack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PH_TrainingTracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestController.cls
public class TestController {
    @AuraEnabled
    public static List<AssessmentLineItem__c> getAssessmentLineItems(Id contactId, Id createdAssessment) {
        system.debug('Contact Id : ' + contactId);
        system.debug('Assessment Id : ' + createdAssessment);
        
        if ([SELECT Id FROM PH_Assessment__c WHERE Contact__c = :contactId].size() == 1)
            return createAssessmentLineItemsWhenPanelCreated(contactId, createdAssessment);
        else
            return createAssessmentLineItemsWhenPanelCreated(contactId, createdAssessment);
            //return createAssessmentLineItemsForRepanelTopics(contactId);
        /*return [SELECT Id, Score__c, maxScore__c, Comment__c, PanelCategory__r.Name 
FROM AssessmentLineItem__c 
WHERE PH_Assessment__r.Contact__c = :contactId AND CreatedDate = TODAY];
*/
    }
    
    @AuraEnabled
    public static List<AssessmentLineItem__c> createAssessmentLineItemsWhenPanelCreated(Id contactId, Id assessmentId) {
        // create new Assessment record
        //PH_Assessment__c panel = new PH_Assessment__c();
        //panel.RecordTypeId = '0121g0000003XJQAA2';
        
        
        // Get training assignment associated with contact
        PH_TrainingAssignment__c ta = [SELECT Id, PH_Training__c, Name FROM PH_TrainingAssignment__c WHERE Contact__c = :contactId ORDER BY CreatedDate DESC LIMIT 1];
        System.debug('ta: ' + ta);
        
        // Get Training associated with training assignment
        PH_Training__c training = [SELECT Id, PH_TrainingTrack__c, Name FROM PH_Training__c WHERE Id = :ta.PH_Training__c ORDER BY CreatedDate DESC LIMIT 1];     
        System.debug('training: ' + training);
        
        // Get training track associated with training
        PH_TrainingTrack__c track = [SELECT Id, Name FROM PH_TrainingTrack__c WHERE Id = :training.PH_TrainingTrack__c];
        System.debug('track: ' + track);
        
        // Get the panel categories for that training track
        List<PanelCategory__c> categories = [SELECT Id, maxScore__c, Name FROM PanelCategory__c WHERE PH_TrainingTrack__c = :track.Id];
        System.debug('categories: ' + categories);
        
        // Create new assessment line items based on categories for insert
        List<AssessmentLineItem__c> assessmentLineItems = new List<AssessmentLineItem__c>();
        for (PanelCategory__c category : categories) {
            AssessmentLineItem__c ali = new AssessmentLineItem__c();
            System.debug('new ali created');
            ali.PanelCategory__c = category.Id;
            ali.PH_Assessment__c = assessmentId;
            ali.maxScore__c = category.maxScore__c;
            ali.PanelCategoryName__c = category.Name;
            System.debug('new ali updated. Name: ' + ali.PanelCategoryName__c);
            assessmentLineItems.add(ali);
        }
        
        insert assessmentLineItems;
        system.Debug('ALIs: ' + assessmentLineItems);
        return assessmentLineItems;
    }
    
    @AuraEnabled
    public static List<AssessmentLineItem__c> createAssessmentLineItemsForRepanelTopics(Id contactId) {
        PH_Assessment__c mostRecentPanel = [SELECT Id FROM PH_Assessment__c WHERE Contact__c = :contactId ORDER BY CreatedDate DESC LIMIT 1];
        
        PH_Assessment__c panel = new PH_Assessment__c();
        panel.RecordTypeId = '0121g0000003XJQAA2';
        
        
        List<AssessmentLineItem__c> topicsToRepanel = [SELECT Id FROM AssessmentLineItem__c WHERE PH_Assessment__c = :mostRecentPanel.Id AND Interviewed__c = false];
        System.debug('Topics to repanel: ' + topicsToRepanel);
        
        List<AssessmentLineItem__c> assessmentLineItems = new List<AssessmentLineItem__c>();
        for (AssessmentLineItem__c ali : topicsToRepanel){
            AssessmentLineItem__c newAli = new AssessmentLineItem__c();
            newAli.PanelCategory__c = ali.PanelCategory__c;
            newAli.PH_Assessment__c = panel.Id;
            newALI.maxScore__c = ali.maxScore__c;
            assessmentLineItems.add(ali);
        }
        insert panel;
        insert assessmentLineItems;
        system.debug('ALIs: ' + assessmentLineItems);
        return assessmentLineItems;
    }
}