force-app/main/default/objects/AssessmentLineItem__c/AssessmentLineItem__c.object-meta.xml
<CustomObject>
    <label>Assessment Line Item</label>
    <nameField>
        <displayFormat>ALI-{0000000}</displayFormat>
        <label>Assessment Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AssessmentLineItem__c/fields/PH_Assessment__c.field-meta.xml
<CustomField>
    <fullName>PH_Assessment__c</fullName>
    <label>PH_Assessment</label>
    <referenceTo>PH_Assessment__c</referenceTo>
    <relationshipLabel>Panel Categories</relationshipLabel>
    <relationshipName>Assessment_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PH_Assessment__c/PH_Assessment__c.object-meta.xml
<CustomObject>
    <label>PH_Assessment</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>PH_Assesment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PH_Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AssessmentServer.cls
public class AssessmentServer 
{
	@auraEnabled
    public static List<AssessmentLineItem__c> returnAssesments(PH_Assessment__c assessment)
    {
        //grab assessment line items where assessment = id
        List<AssessmentLineItem__c> assessments = new List <AssessmentLineItem__c>();
        
        List<AssessmentLineItem__c> assessmentLineItem = [SELECT Status__c FROM AssessmentLineItem__c WHERE PH_Assessment__c =: assessment.Id];

        for(AssessmentLineItem__c lineItem : assessmentLineItem)
        {
            if(lineItem.Status__c == False)
            {
				assessments.add(lineItem);
            }
        }
        return assessments;
    }
    @auraEnabled
    public static List<PH_Assessment__c> getAssessmentId(Id contactId)
    {
Contact retrievedContact = [SELECT Name, (SELECT Id FROM PH_Assessments__r) FROM Contact WHERE Id =: ContactId];
        return retrievedContact.PH_Assessments__r;    
    }
}