force-app/main/default/objects/AssessmentLineItem__c/AssessmentLineItem__c.object-meta.xml
<CustomObject>
    <label>Assessment Line Item</label>
    <nameField>
        <displayFormat>ALI-{0000000}</displayFormat>
        <label>Assessment Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AssessmentLineItem__c/fields/PH_Assessment__c.field-meta.xml
<CustomField>
    <fullName>PH_Assessment__c</fullName>
    <label>PH_Assessment</label>
    <referenceTo>PH_Assessment__c</referenceTo>
    <relationshipLabel>Panel Categories</relationshipLabel>
    <relationshipName>Assessment_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PH_Assessment__c/PH_Assessment__c.object-meta.xml
<CustomObject>
    <label>PH_Assessment</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>PH_Assesment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PH_Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Stamp__c/Time_Stamp__c.object-meta.xml
<CustomObject>
    <label>Time Stamp</label>
    <nameField>
        <label>Time_Stamp Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Stamps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Stamp__c/fields/milliSecs__c.field-meta.xml
<CustomField>
    <fullName>milliSecs__c</fullName>
    <label>milliSecs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time_Stamp__c/fields/PH_Assessment__c.field-meta.xml
<CustomField>
    <fullName>PH_Assessment__c</fullName>
    <label>PH_Assessment</label>
    <referenceTo>PH_Assessment__c</referenceTo>
    <relationshipLabel>Time Stamps</relationshipLabel>
    <relationshipName>Time_Stamps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/InterviewMainMiscApexController.cls
public without sharing class InterviewMainMiscApexController {
  
    @AuraEnabled
    public static void insertTimeStamp(List<Integer> sTimeStamp, PH_Assessment__c phAss){
        List<Time_Stamp__c> tsList = new List<Time_Stamp__c>();     
        for(Integer stm : sTimeStamp){
            Time_Stamp__c ts = new Time_Stamp__c();
            Integer ran = Integer.valueof((math.random() * 100000));
            ts.Name = 'Time Stamp ' + String.valueof(ran);
            ts.milliSecs__c = stm;
            ts.PH_Assessment__c = phAss.Id;
            tsList.add(ts);
        }

        insert tsList;
    }

    @AuraEnabled
    public static void updateCategory(AssessmentLineItem__c AssLineItem){
        update AssLineItem;
    }

}