force-app/main/default/objects/AssessmentLineItem__c/AssessmentLineItem__c.object-meta.xml
<CustomObject>
    <label>Assessment Line Item</label>
    <nameField>
        <displayFormat>ALI-{0000000}</displayFormat>
        <label>Assessment Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AssessmentLineItem__c/fields/Interviewed__c.field-meta.xml
<CustomField>
    <fullName>Interviewed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Passed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AssessmentLineItem__c/fields/maxScore__c.field-meta.xml
<CustomField>
    <fullName>maxScore__c</fullName>
    <label>maxScore</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/InterviewMainController.cls
public class InterviewMainController {
    
    @AuraEnabled
    public static List<AssessmentLineItem__c> getUpdatedCategories(List<AssessmentLineItem__c> oldRecs){
        List<AssessmentLineItem__c> newRecs = [SELECT Id, Name, Score__c, maxScore__c, Status__c, Interviewed__c, Comment__c 
                                               FROM AssessmentLineItem__c WHERE Id IN :oldRecs];
        /*for(Integer n = 0; n < newRecs.size(); n++){
            AssessmentLineItem__c newCat = newRecs[n];
            AssessmentLineItem__c oldCat = oldRecs[n];


        }*/

        return newRecs;
    }

}