force-app/main/default/objects/AssessmentLineItem__c/AssessmentLineItem__c.object-meta.xml
<CustomObject>
    <label>Assessment Line Item</label>
    <nameField>
        <displayFormat>ALI-{0000000}</displayFormat>
        <label>Assessment Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AssessmentLineItem__c/fields/Interviewed__c.field-meta.xml
<CustomField>
    <fullName>Interviewed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Passed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AssessmentLineItem__c/fields/PH_Assessment__c.field-meta.xml
<CustomField>
    <fullName>PH_Assessment__c</fullName>
    <label>PH_Assessment</label>
    <referenceTo>PH_Assessment__c</referenceTo>
    <relationshipLabel>Panel Categories</relationshipLabel>
    <relationshipName>Assessment_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PH_Assessment__c/PH_Assessment__c.object-meta.xml
<CustomObject>
    <label>PH_Assessment</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>PH_Assesment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PH_Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PH_Assessment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PH_Assessments</relationshipLabel>
    <relationshipName>PH_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateAliControllerTest.cls
@isTest
public class CreateAliControllerTest {

    @TestSetup
    public static void setup(){
        PanelForceDataCreator.createData();  // associates panelcategories trainings  training tracks
      
    }
    
    @isTest
    public static void getAssessmentLineItemsTest(){
        Id associateId = [SELECT id FROM Contact LIMIT 1].id;
        PH_Assessment__c assessment = new PH_Assessment__c(Contact__c=associateId);
        insert assessment;
        List<AssessmentLineItem__c> assessmentLineItems = createALIController.getAssessmentLineItems(associateId, assessment.id);
        Integer totalNumLineItems = assessmentLineItems.size();
        System.assertNotEquals(0, totalNumLineItems); //there should be some lineItems
        
        // set all to a pass initially
        for(AssessmentLineItem__c ali : assessmentLineItems){
            ali.interviewed__c = true;
        }
        
        AssessmentLineItem__c failedALI1 = assessmentLineItems[0];
        AssessmentLineItem__c failedALI2 = assessmentLineItems[assessmentLineItems.size()-1];
        failedALI1.interviewed__c = false; //failure!
        failedALI2.interviewed__c = false;
        
        update assessmentLineItems;
        // insert new assessment 
        PH_Assessment__c assessment2 = new PH_Assessment__c(Contact__c=associateId);
        insert assessment2;
        
        assessmentLineItems = createALIController.getAssessmentLineItems(associateId, assessment2.id); //this list should only contained the failed ALIs
        System.assertEquals(2, assessmentLineItems.size());
        
    }
}