force-app/main/default/objects/AssessmentLineItem__c/AssessmentLineItem__c.object-meta.xml
<CustomObject>
    <label>Assessment Line Item</label>
    <nameField>
        <displayFormat>ALI-{0000000}</displayFormat>
        <label>Assessment Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AssessmentLineItem__c/fields/PH_Assessment__c.field-meta.xml
<CustomField>
    <fullName>PH_Assessment__c</fullName>
    <label>PH_Assessment</label>
    <referenceTo>PH_Assessment__c</referenceTo>
    <relationshipLabel>Panel Categories</relationshipLabel>
    <relationshipName>Assessment_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PH_Assessment__c/PH_Assessment__c.object-meta.xml
<CustomObject>
    <label>PH_Assessment</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>PH_Assesment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PH_Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/InterviewMainMiscApexControllerTests.cls
@isTest(seeAllData=true)
public class InterviewMainMiscApexControllerTests {
	@isTest
    static void testAll() {
        InterviewMainMiscApexController.insertTimeStamp(new List<Integer>{1,4,5}, [SELECT Id FROM PH_Assessment__c WHERE Id = 'a012K000020Jb4IQAS']);
        InterviewMainMiscApexController.totalTimeDiff(5, [SELECT Id FROM PH_Assessment__c WHERE Id = 'a012K000020Jb4IQAS' LIMIT 1]);
        InterviewMainMiscApexController.updateCategory([SELECT Id FROM AssessmentLineItem__c WHERE Id = 'a002K00000qPd8RQAS' LIMIT 1]);
    }
}