force-app/main/default/objects/AssessmentLineItem__c/AssessmentLineItem__c.object-meta.xml
<CustomObject>
    <label>Assessment Line Item</label>
    <nameField>
        <displayFormat>ALI-{0000000}</displayFormat>
        <label>Assessment Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AssessmentLineItem__c/fields/PH_Assessment__c.field-meta.xml
<CustomField>
    <fullName>PH_Assessment__c</fullName>
    <label>PH_Assessment</label>
    <referenceTo>PH_Assessment__c</referenceTo>
    <relationshipLabel>Panel Categories</relationshipLabel>
    <relationshipName>Assessment_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PH_Assessment__c/PH_Assessment__c.object-meta.xml
<CustomObject>
    <label>PH_Assessment</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>PH_Assesment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PH_Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PH_Assessment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PH_Assessments</relationshipLabel>
    <relationshipName>PH_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AssessmentControllerTest.cls
@isTest
public class AssessmentControllerTest 
{
 
	@isTest
    public static void testReturnAssesments()
    {
        //create new assessment for testing 
        PH_Assessment__c newAssessment = new PH_Assessment__c();
 		//create new contact for testing
        Contact panelist = new Contact();
        //call assessment controller with test contact and assessment 
        List <AssessmentLineItem__c> returnedAssessments = AssessmentController.returnAssessments(panelist.Id,newAssessment);
        //loop through returned list 
		for(AssessmentLineItem__c lineItem : returnedAssessments)
        {
            //validate ids are equal
            System.assertEquals(newAssessment.Id, lineItem.Id);
            //make sure status is false: panelist failed
            System.assertEquals(lineItem.Status__c, false);
            //validate that the contact passed in is the same contact for the assessment
            System.assertEquals(lineItem.PH_Assessment__r.Contact__c, panelist.Id);
        }
    }
  
}