force-app/main/default/objects/AssessmentLineItem__c/AssessmentLineItem__c.object-meta.xml
<CustomObject>
    <label>Assessment Line Item</label>
    <nameField>
        <displayFormat>ALI-{0000000}</displayFormat>
        <label>Assessment Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AssessmentLineItem__c/fields/Interviewed__c.field-meta.xml
<CustomField>
    <fullName>Interviewed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Passed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AssessmentLineItem__c/fields/PanelCategory__c.field-meta.xml
<CustomField>
    <fullName>PanelCategory__c</fullName>
    <label>Panel Category</label>
    <referenceTo>PanelCategory__c</referenceTo>
    <relationshipName>Assessment_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AssessmentLineItem__c/fields/PH_Assessment__c.field-meta.xml
<CustomField>
    <fullName>PH_Assessment__c</fullName>
    <label>PH_Assessment</label>
    <referenceTo>PH_Assessment__c</referenceTo>
    <relationshipLabel>Panel Categories</relationshipLabel>
    <relationshipName>Assessment_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PanelCategory__c/PanelCategory__c.object-meta.xml
<CustomObject>
    <label>Panel Category</label>
    <nameField>
        <label>Panel Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Panel Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PH_Assessment__c/PH_Assessment__c.object-meta.xml
<CustomObject>
    <label>PH_Assessment</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>PH_Assesment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PH_Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PH_Assessment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PH_Assessments</relationshipLabel>
    <relationshipName>PH_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AssessmentLineItemControllerTest.cls
@isTest
public class AssessmentLineItemControllerTest{
    @TestSetup
    static void setup(){
        PanelForceDataCreator.CreateData();
        Id PC = [SELECT Id FROM PanelCategory__c LIMIT 1].Id;
        
        Contact c = [SELECT Id FROM Contact LIMIT 1];
        
        PH_Assessment__c Assessment = new PH_Assessment__c (Contact__c=c.Id);
        
        insert Assessment;
        
        AssessmentLineItem__c ALI = new AssessmentLineItem__c(PanelCategory__c = PC, PH_Assessment__c = Assessment.Id, score__c=10, comment__c ='nice job', interviewed__c = false);
        
        
        insert ALI;
    }
    
    @isTest static void testSaveALI(){
        //AssessmentLineItemController ALIC = new AssessmentLineItemController();
        AssessmentLineItem__c ALI = [SELECT Id, score__c, comment__c, interviewed__c FROM AssessmentLineItem__c];
        
        Id ALIId = ALI.Id;
        
        AssessmentLineItemController.saveALI(ALIId, 5, 'Blah', true);
        //System.assertEquals([SELECT Id, score__c, comment__c, interviewed__c FROM AssessmentLineItem__c] );
        ALI = [SELECT Id, score__c, comment__c, interviewed__c FROM AssessmentLineItem__c WHERE Id =: ALIId];
        System.assertEquals(5, ALI.Score__c);
        System.assertEquals('Blah', ALI.comment__c);
        System.assertEquals(false, ALI.interviewed__c);
        
    }
    
}