force-app/main/default/objects/AssessmentLineItem__c/AssessmentLineItem__c.object-meta.xml
<CustomObject>
    <label>Assessment Line Item</label>
    <nameField>
        <displayFormat>ALI-{0000000}</displayFormat>
        <label>Assessment Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AssessmentLineItem__c/fields/Interviewed__c.field-meta.xml
<CustomField>
    <fullName>Interviewed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Passed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AssessmentLineItemController.cls
public class AssessmentLineItemController{
    @AuraEnabled
    public static void saveALI(id ALIId, integer score, string comments, boolean repanel){
        System.debug('inside saveALI');
        AssessmentLineItem__c ALI = new AssessmentLineItem__c();
        ALI.id = ALIId;
        ALI.score__C = score;
        ALI.comment__C = comments;
        ALI.interviewed__c = repanel;

        System.debug(ALI);
        update ALI;
    }
}