force-app/main/default/objects/PH_Training__c/PH_Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <displayFormat>TRNG-{00000000}</displayFormat>
        <label>PH_ Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PH_Training__c/fields/PH_TrainingTrack__c.field-meta.xml
<CustomField>
    <fullName>PH_TrainingTrack__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PH_TrainingTrack</label>
    <referenceTo>PH_TrainingTrack__c</referenceTo>
    <relationshipLabel>PH_Trainings</relationshipLabel>
    <relationshipName>PH_Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PH_TrainingAssignment__c/PH_TrainingAssignment__c.object-meta.xml
<CustomObject>
    <label>Training Assignment</label>
    <nameField>
        <displayFormat>TA-{00000000}</displayFormat>
        <label>PH_Training  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PH_TrainingAssignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PH_TrainingAssignments</relationshipLabel>
    <relationshipName>PH_TrainingAssignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PH_TrainingAssignment__c/fields/PH_Training__c.field-meta.xml
<CustomField>
    <fullName>PH_Training__c</fullName>
    <label>PH_Training</label>
    <referenceTo>PH_Training__c</referenceTo>
    <relationshipLabel>PH_TrainingAssignments</relationshipLabel>
    <relationshipName>PH_TrainingAssignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PH_TrainingTrack__c/PH_TrainingTrack__c.object-meta.xml
<CustomObject>
    <label>PH_TrainingTrack</label>
    <nameField>
        <label>PH_TrainingTrack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PH_TrainingTracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TrackController.cls
public with sharing class TrackController {
    // class for passing information back to InterviewInitial component.
    @AuraEnabled
    public static Account getAccount(Id accountId) {
        // may be needed later
        return [SELECT Id, Name  FROM Account LIMIT 1];
    }

    @AuraEnabled
    public static String getContact(Id contactId) {
        // method to get the Contact record for InterviewInitial component.
        List<Contact> cl = new List<Contact>();
        String lastName;

        cl = [SELECT Id, Lastname, Firstname FROM Contact WHERE Id = :contactId];
        for (Contact c : cl) {
                System.debug(c.Lastname);
                if (c.Id == contactId) {
                    System.debug(c.Id + ' ' + c.Lastname);
                    lastName = c.Lastname;
                }
        }
        return lastName;
    }

    @AuraEnabled
    Public Static String getTrack(Id contactId) {
        // method to get the Track Name for the InterviewInitial component.
        String trackName;
        trackName = [SELECT PH_TrainingTrack__r.Name FROM PH_Training__c WHERE Id IN (SELECT PH_Training__c FROM PH_TrainingAssignment__c WHERE Contact__c = :contactId)][0].PH_TrainingTrack__r.Name;
        return trackName;
    }

    // There's no direct relationship in the data model
    // hence the SOQL statement below.
    //public cody() {
    //    [SELECT PH_TrainingTrack__r.Name FROM PH_Training__c
    //    WHERE Id IN (SELECT PH_Training__c FROM PH_TrainingAssignment__c WHERE Contact__c = :contactId)][0].PH_TrainingTrack__r.Name;
    //}

    public TrackController() {

    }
}